site_name: Velike Igre
repo_url: https://github.com/samolego/VelikeIgre

theme:
  name: material
  language: sl
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/child

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - search.highlight
    - header.autohide
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Temni način
      primary: orange

    - scheme: slate 
      toggle:
        icon: material/lightbulb-outline
        name: Svetli način

      primary: lime

edit_uri: edit/master/docs/

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - git-revision-date-localized:
      type: date